import { Space_Grotesk } from "next/font/google";
import local from "next/font/local";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-spaceGrotesk",
  weight : "400"
});

// const LSFont = local({
//   src: [
//     {
//       path: "../public/fonts/LSANS.TTF",
//       // weight: "400",
//     },
//   ],
//   variable: "--font-LSFont",
// });
// ${LSFont.variable}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable}`}>
        {children}
      </body>
    </html>
  );
}
